/* 
 * Woolball AI Network API
 *
 * **Transform idle browsers into a powerful distributed AI inference network**  For detailed examples and model lists, visit our [GitHub repository](https://github.com/woolball-xyz/woolball-server).
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using NUnit.Framework;

using IO.Swagger.Client;
using IO.Swagger.Api;
using IO.Swagger.Model;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing SpeechRecognitionApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    [TestFixture]
    public class SpeechRecognitionApiTests
    {
        private SpeechRecognitionApi instance;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new SpeechRecognitionApi();
        }

        /// <summary>
        /// Clean up after each unit test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of SpeechRecognitionApi
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOfType' SpeechRecognitionApi
            //Assert.IsInstanceOfType(typeof(SpeechRecognitionApi), instance, "instance is a SpeechRecognitionApi");
        }

        /// <summary>
        /// Test SpeechToText
        /// </summary>
        [Test]
        public void SpeechToTextTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string model = null;
            //string dtype = null;
            //Object input = null;
            //string returnTimestamps = null;
            //bool? stream = null;
            //int? chunkLengthS = null;
            //int? strideLengthS = null;
            //bool? forceFullSequences = null;
            //string language = null;
            //string task = null;
            //int? numFrames = null;
            //var response = instance.SpeechToText(model, dtype, input, returnTimestamps, stream, chunkLengthS, strideLengthS, forceFullSequences, language, task, numFrames);
            //Assert.IsInstanceOf<List<STTChunk>> (response, "response is List<STTChunk>");
        }
    }

}
