/* 
 * Woolball AI Network API
 *
 * **Transform idle browsers into a powerful distributed AI inference network**  For detailed examples and model lists, visit our [GitHub repository](https://github.com/woolball-xyz/woolball-server).
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using NUnit.Framework;

using IO.Swagger.Client;
using IO.Swagger.Api;
using IO.Swagger.Model;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing TextGenerationApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    [TestFixture]
    public class TextGenerationApiTests
    {
        private TextGenerationApi instance;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new TextGenerationApi();
        }

        /// <summary>
        /// Clean up after each unit test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of TextGenerationApi
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOfType' TextGenerationApi
            //Assert.IsInstanceOfType(typeof(TextGenerationApi), instance, "instance is a TextGenerationApi");
        }

        /// <summary>
        /// Test TextGeneration
        /// </summary>
        [Test]
        public void TextGenerationTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string provider = null;
            //string model = null;
            //string input = null;
            //int? topK = null;
            //double? topP = null;
            //double? temperature = null;
            //double? repetitionPenalty = null;
            //string dtype = null;
            //int? maxLength = null;
            //int? maxNewTokens = null;
            //int? minLength = null;
            //int? minNewTokens = null;
            //bool? doSample = null;
            //int? numBeams = null;
            //int? noRepeatNgramSize = null;
            //int? contextWindowSize = null;
            //int? slidingWindowSize = null;
            //int? attentionSinkSize = null;
            //double? frequencyPenalty = null;
            //double? presencePenalty = null;
            //int? bosTokenId = null;
            //int? maxTokens = null;
            //int? randomSeed = null;
            //var response = instance.TextGeneration(provider, model, input, topK, topP, temperature, repetitionPenalty, dtype, maxLength, maxNewTokens, minLength, minNewTokens, doSample, numBeams, noRepeatNgramSize, contextWindowSize, slidingWindowSize, attentionSinkSize, frequencyPenalty, presencePenalty, bosTokenId, maxTokens, randomSeed);
            //Assert.IsInstanceOf<TextGenerationResponse> (response, "response is TextGenerationResponse");
        }
    }

}
