/* 
 * Woolball AI Network API
 *
 * **Transform idle browsers into a powerful distributed AI inference network**  For detailed examples and model lists, visit our [GitHub repository](https://github.com/woolball-xyz/woolball-server).
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using NUnit.Framework;

using IO.Swagger.Client;
using IO.Swagger.Api;
using IO.Swagger.Model;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing TranslationApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    [TestFixture]
    public class TranslationApiTests
    {
        private TranslationApi instance;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new TranslationApi();
        }

        /// <summary>
        /// Clean up after each unit test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of TranslationApi
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOfType' TranslationApi
            //Assert.IsInstanceOfType(typeof(TranslationApi), instance, "instance is a TranslationApi");
        }

        /// <summary>
        /// Test Translation
        /// </summary>
        [Test]
        public void TranslationTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string model = null;
            //string dtype = null;
            //string input = null;
            //string srcLang = null;
            //string tgtLang = null;
            //var response = instance.Translation(model, dtype, input, srcLang, tgtLang);
            //Assert.IsInstanceOf<TranslationResponse> (response, "response is TranslationResponse");
        }
    }

}
