/* 
 * Woolball AI Network API
 *
 * **Transform idle browsers into a powerful distributed AI inference network**  For detailed examples and model lists, visit our [GitHub repository](https://github.com/woolball-xyz/woolball-server).
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
namespace IO.Swagger.Model
{
    /// <summary>
    /// OneOfSpeechToTextRequestContractInput
    /// </summary>
    public interface OneOfSpeechToTextRequestContractInput
    {
    
    }
}
