/* 
 * Woolball AI Network API
 *
 * **Transform idle browsers into a powerful distributed AI inference network**  For detailed examples and model lists, visit our [GitHub repository](https://github.com/woolball-xyz/woolball-server).
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = IO.Swagger.Client.SwaggerDateConverter;
namespace IO.Swagger.Model
{
    /// <summary>
    /// TextGenerationResponse
    /// </summary>
    [DataContract]
        public partial class TextGenerationResponse :  IEquatable<TextGenerationResponse>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="TextGenerationResponse" /> class.
        /// </summary>
        /// <param name="generatedText">generatedText.</param>
        public TextGenerationResponse(string generatedText = default(string))
        {
            this.GeneratedText = generatedText;
        }
        
        /// <summary>
        /// Gets or Sets GeneratedText
        /// </summary>
        [DataMember(Name="generatedText", EmitDefaultValue=false)]
        public string GeneratedText { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class TextGenerationResponse {\n");
            sb.Append("  GeneratedText: ").Append(GeneratedText).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as TextGenerationResponse);
        }

        /// <summary>
        /// Returns true if TextGenerationResponse instances are equal
        /// </summary>
        /// <param name="input">Instance of TextGenerationResponse to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(TextGenerationResponse input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.GeneratedText == input.GeneratedText ||
                    (this.GeneratedText != null &&
                    this.GeneratedText.Equals(input.GeneratedText))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.GeneratedText != null)
                    hashCode = hashCode * 59 + this.GeneratedText.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }
}
