/* 
 * Woolball AI Network API
 *
 * **Transform idle browsers into a powerful distributed AI inference network**  For detailed examples and model lists, visit our [GitHub repository](https://github.com/woolball-xyz/woolball-server).
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = IO.Swagger.Client.SwaggerDateConverter;
namespace IO.Swagger.Model
{
    /// <summary>
    /// TranslationRequestContract
    /// </summary>
    [DataContract]
        public partial class TranslationRequestContract :  IEquatable<TranslationRequestContract>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="TranslationRequestContract" /> class.
        /// </summary>
        /// <param name="model">model (required).</param>
        /// <param name="dtype">dtype (required).</param>
        /// <param name="input">input (required).</param>
        /// <param name="srcLang">srcLang (required).</param>
        /// <param name="tgtLang">tgtLang (required).</param>
        public TranslationRequestContract(string model = default(string), string dtype = default(string), string input = default(string), string srcLang = default(string), string tgtLang = default(string))
        {
            // to ensure "model" is required (not null)
            if (model == null)
            {
                throw new InvalidDataException("model is a required property for TranslationRequestContract and cannot be null");
            }
            else
            {
                this.Model = model;
            }
            // to ensure "dtype" is required (not null)
            if (dtype == null)
            {
                throw new InvalidDataException("dtype is a required property for TranslationRequestContract and cannot be null");
            }
            else
            {
                this.Dtype = dtype;
            }
            // to ensure "input" is required (not null)
            if (input == null)
            {
                throw new InvalidDataException("input is a required property for TranslationRequestContract and cannot be null");
            }
            else
            {
                this.Input = input;
            }
            // to ensure "srcLang" is required (not null)
            if (srcLang == null)
            {
                throw new InvalidDataException("srcLang is a required property for TranslationRequestContract and cannot be null");
            }
            else
            {
                this.SrcLang = srcLang;
            }
            // to ensure "tgtLang" is required (not null)
            if (tgtLang == null)
            {
                throw new InvalidDataException("tgtLang is a required property for TranslationRequestContract and cannot be null");
            }
            else
            {
                this.TgtLang = tgtLang;
            }
        }
        
        /// <summary>
        /// Gets or Sets Model
        /// </summary>
        [DataMember(Name="model", EmitDefaultValue=false)]
        public string Model { get; set; }

        /// <summary>
        /// Gets or Sets Dtype
        /// </summary>
        [DataMember(Name="dtype", EmitDefaultValue=false)]
        public string Dtype { get; set; }

        /// <summary>
        /// Gets or Sets Input
        /// </summary>
        [DataMember(Name="input", EmitDefaultValue=false)]
        public string Input { get; set; }

        /// <summary>
        /// Gets or Sets SrcLang
        /// </summary>
        [DataMember(Name="srcLang", EmitDefaultValue=false)]
        public string SrcLang { get; set; }

        /// <summary>
        /// Gets or Sets TgtLang
        /// </summary>
        [DataMember(Name="tgtLang", EmitDefaultValue=false)]
        public string TgtLang { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class TranslationRequestContract {\n");
            sb.Append("  Model: ").Append(Model).Append("\n");
            sb.Append("  Dtype: ").Append(Dtype).Append("\n");
            sb.Append("  Input: ").Append(Input).Append("\n");
            sb.Append("  SrcLang: ").Append(SrcLang).Append("\n");
            sb.Append("  TgtLang: ").Append(TgtLang).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as TranslationRequestContract);
        }

        /// <summary>
        /// Returns true if TranslationRequestContract instances are equal
        /// </summary>
        /// <param name="input">Instance of TranslationRequestContract to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(TranslationRequestContract input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Model == input.Model ||
                    (this.Model != null &&
                    this.Model.Equals(input.Model))
                ) && 
                (
                    this.Dtype == input.Dtype ||
                    (this.Dtype != null &&
                    this.Dtype.Equals(input.Dtype))
                ) && 
                (
                    this.Input == input.Input ||
                    (this.Input != null &&
                    this.Input.Equals(input.Input))
                ) && 
                (
                    this.SrcLang == input.SrcLang ||
                    (this.SrcLang != null &&
                    this.SrcLang.Equals(input.SrcLang))
                ) && 
                (
                    this.TgtLang == input.TgtLang ||
                    (this.TgtLang != null &&
                    this.TgtLang.Equals(input.TgtLang))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Model != null)
                    hashCode = hashCode * 59 + this.Model.GetHashCode();
                if (this.Dtype != null)
                    hashCode = hashCode * 59 + this.Dtype.GetHashCode();
                if (this.Input != null)
                    hashCode = hashCode * 59 + this.Input.GetHashCode();
                if (this.SrcLang != null)
                    hashCode = hashCode * 59 + this.SrcLang.GetHashCode();
                if (this.TgtLang != null)
                    hashCode = hashCode * 59 + this.TgtLang.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }
}
