/* 
 * Woolball AI Network API
 *
 * **Transform idle browsers into a powerful distributed AI inference network**  For detailed examples and model lists, visit our [GitHub repository](https://github.com/woolball-xyz/woolball-server).
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing SpeechToTextRequestContract
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class SpeechToTextRequestContractTests
    {
        // TODO uncomment below to declare an instance variable for SpeechToTextRequestContract
        //private SpeechToTextRequestContract instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of SpeechToTextRequestContract
            //instance = new SpeechToTextRequestContract();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of SpeechToTextRequestContract
        /// </summary>
        [Test]
        public void SpeechToTextRequestContractInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" SpeechToTextRequestContract
            //Assert.IsInstanceOfType<SpeechToTextRequestContract> (instance, "variable 'instance' is a SpeechToTextRequestContract");
        }


        /// <summary>
        /// Test the property 'Model'
        /// </summary>
        [Test]
        public void ModelTest()
        {
            // TODO unit test for the property 'Model'
        }
        /// <summary>
        /// Test the property 'Dtype'
        /// </summary>
        [Test]
        public void DtypeTest()
        {
            // TODO unit test for the property 'Dtype'
        }
        /// <summary>
        /// Test the property 'Input'
        /// </summary>
        [Test]
        public void InputTest()
        {
            // TODO unit test for the property 'Input'
        }
        /// <summary>
        /// Test the property 'ReturnTimestamps'
        /// </summary>
        [Test]
        public void ReturnTimestampsTest()
        {
            // TODO unit test for the property 'ReturnTimestamps'
        }
        /// <summary>
        /// Test the property 'Stream'
        /// </summary>
        [Test]
        public void StreamTest()
        {
            // TODO unit test for the property 'Stream'
        }
        /// <summary>
        /// Test the property 'ChunkLengthS'
        /// </summary>
        [Test]
        public void ChunkLengthSTest()
        {
            // TODO unit test for the property 'ChunkLengthS'
        }
        /// <summary>
        /// Test the property 'StrideLengthS'
        /// </summary>
        [Test]
        public void StrideLengthSTest()
        {
            // TODO unit test for the property 'StrideLengthS'
        }
        /// <summary>
        /// Test the property 'ForceFullSequences'
        /// </summary>
        [Test]
        public void ForceFullSequencesTest()
        {
            // TODO unit test for the property 'ForceFullSequences'
        }
        /// <summary>
        /// Test the property 'Language'
        /// </summary>
        [Test]
        public void LanguageTest()
        {
            // TODO unit test for the property 'Language'
        }
        /// <summary>
        /// Test the property 'Task'
        /// </summary>
        [Test]
        public void TaskTest()
        {
            // TODO unit test for the property 'Task'
        }
        /// <summary>
        /// Test the property 'NumFrames'
        /// </summary>
        [Test]
        public void NumFramesTest()
        {
            // TODO unit test for the property 'NumFrames'
        }

    }

}
