/* 
 * Woolball AI Network API
 *
 * **Transform idle browsers into a powerful distributed AI inference network**  For detailed examples and model lists, visit our [GitHub repository](https://github.com/woolball-xyz/woolball-server).
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing TextGenerationRequestContract
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class TextGenerationRequestContractTests
    {
        // TODO uncomment below to declare an instance variable for TextGenerationRequestContract
        //private TextGenerationRequestContract instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of TextGenerationRequestContract
            //instance = new TextGenerationRequestContract();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of TextGenerationRequestContract
        /// </summary>
        [Test]
        public void TextGenerationRequestContractInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" TextGenerationRequestContract
            //Assert.IsInstanceOfType<TextGenerationRequestContract> (instance, "variable 'instance' is a TextGenerationRequestContract");
        }


        /// <summary>
        /// Test the property 'Provider'
        /// </summary>
        [Test]
        public void ProviderTest()
        {
            // TODO unit test for the property 'Provider'
        }
        /// <summary>
        /// Test the property 'Model'
        /// </summary>
        [Test]
        public void ModelTest()
        {
            // TODO unit test for the property 'Model'
        }
        /// <summary>
        /// Test the property 'Input'
        /// </summary>
        [Test]
        public void InputTest()
        {
            // TODO unit test for the property 'Input'
        }
        /// <summary>
        /// Test the property 'TopK'
        /// </summary>
        [Test]
        public void TopKTest()
        {
            // TODO unit test for the property 'TopK'
        }
        /// <summary>
        /// Test the property 'TopP'
        /// </summary>
        [Test]
        public void TopPTest()
        {
            // TODO unit test for the property 'TopP'
        }
        /// <summary>
        /// Test the property 'Temperature'
        /// </summary>
        [Test]
        public void TemperatureTest()
        {
            // TODO unit test for the property 'Temperature'
        }
        /// <summary>
        /// Test the property 'RepetitionPenalty'
        /// </summary>
        [Test]
        public void RepetitionPenaltyTest()
        {
            // TODO unit test for the property 'RepetitionPenalty'
        }
        /// <summary>
        /// Test the property 'Dtype'
        /// </summary>
        [Test]
        public void DtypeTest()
        {
            // TODO unit test for the property 'Dtype'
        }
        /// <summary>
        /// Test the property 'MaxLength'
        /// </summary>
        [Test]
        public void MaxLengthTest()
        {
            // TODO unit test for the property 'MaxLength'
        }
        /// <summary>
        /// Test the property 'MaxNewTokens'
        /// </summary>
        [Test]
        public void MaxNewTokensTest()
        {
            // TODO unit test for the property 'MaxNewTokens'
        }
        /// <summary>
        /// Test the property 'MinLength'
        /// </summary>
        [Test]
        public void MinLengthTest()
        {
            // TODO unit test for the property 'MinLength'
        }
        /// <summary>
        /// Test the property 'MinNewTokens'
        /// </summary>
        [Test]
        public void MinNewTokensTest()
        {
            // TODO unit test for the property 'MinNewTokens'
        }
        /// <summary>
        /// Test the property 'DoSample'
        /// </summary>
        [Test]
        public void DoSampleTest()
        {
            // TODO unit test for the property 'DoSample'
        }
        /// <summary>
        /// Test the property 'NumBeams'
        /// </summary>
        [Test]
        public void NumBeamsTest()
        {
            // TODO unit test for the property 'NumBeams'
        }
        /// <summary>
        /// Test the property 'NoRepeatNgramSize'
        /// </summary>
        [Test]
        public void NoRepeatNgramSizeTest()
        {
            // TODO unit test for the property 'NoRepeatNgramSize'
        }
        /// <summary>
        /// Test the property 'ContextWindowSize'
        /// </summary>
        [Test]
        public void ContextWindowSizeTest()
        {
            // TODO unit test for the property 'ContextWindowSize'
        }
        /// <summary>
        /// Test the property 'SlidingWindowSize'
        /// </summary>
        [Test]
        public void SlidingWindowSizeTest()
        {
            // TODO unit test for the property 'SlidingWindowSize'
        }
        /// <summary>
        /// Test the property 'AttentionSinkSize'
        /// </summary>
        [Test]
        public void AttentionSinkSizeTest()
        {
            // TODO unit test for the property 'AttentionSinkSize'
        }
        /// <summary>
        /// Test the property 'FrequencyPenalty'
        /// </summary>
        [Test]
        public void FrequencyPenaltyTest()
        {
            // TODO unit test for the property 'FrequencyPenalty'
        }
        /// <summary>
        /// Test the property 'PresencePenalty'
        /// </summary>
        [Test]
        public void PresencePenaltyTest()
        {
            // TODO unit test for the property 'PresencePenalty'
        }
        /// <summary>
        /// Test the property 'BosTokenId'
        /// </summary>
        [Test]
        public void BosTokenIdTest()
        {
            // TODO unit test for the property 'BosTokenId'
        }
        /// <summary>
        /// Test the property 'MaxTokens'
        /// </summary>
        [Test]
        public void MaxTokensTest()
        {
            // TODO unit test for the property 'MaxTokens'
        }
        /// <summary>
        /// Test the property 'RandomSeed'
        /// </summary>
        [Test]
        public void RandomSeedTest()
        {
            // TODO unit test for the property 'RandomSeed'
        }

    }

}
