/* 
 * Woolball AI Network API
 *
 * **Transform idle browsers into a powerful distributed AI inference network**  For detailed examples and model lists, visit our [GitHub repository](https://github.com/woolball-xyz/woolball-server).
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing TextToSpeechRequestContract
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class TextToSpeechRequestContractTests
    {
        // TODO uncomment below to declare an instance variable for TextToSpeechRequestContract
        //private TextToSpeechRequestContract instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of TextToSpeechRequestContract
            //instance = new TextToSpeechRequestContract();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of TextToSpeechRequestContract
        /// </summary>
        [Test]
        public void TextToSpeechRequestContractInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" TextToSpeechRequestContract
            //Assert.IsInstanceOfType<TextToSpeechRequestContract> (instance, "variable 'instance' is a TextToSpeechRequestContract");
        }


        /// <summary>
        /// Test the property 'Model'
        /// </summary>
        [Test]
        public void ModelTest()
        {
            // TODO unit test for the property 'Model'
        }
        /// <summary>
        /// Test the property 'Dtype'
        /// </summary>
        [Test]
        public void DtypeTest()
        {
            // TODO unit test for the property 'Dtype'
        }
        /// <summary>
        /// Test the property 'Input'
        /// </summary>
        [Test]
        public void InputTest()
        {
            // TODO unit test for the property 'Input'
        }
        /// <summary>
        /// Test the property 'Voice'
        /// </summary>
        [Test]
        public void VoiceTest()
        {
            // TODO unit test for the property 'Voice'
        }
        /// <summary>
        /// Test the property 'Stream'
        /// </summary>
        [Test]
        public void StreamTest()
        {
            // TODO unit test for the property 'Stream'
        }

    }

}
