/* 
 * Woolball AI Network API
 *
 * **Transform idle browsers into a powerful distributed AI inference network**  For detailed examples and model lists, visit our [GitHub repository](https://github.com/woolball-xyz/woolball-server).
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing TextGenerationResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class TextGenerationResponseTests
    {
        // TODO uncomment below to declare an instance variable for TextGenerationResponse
        //private TextGenerationResponse instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of TextGenerationResponse
            //instance = new TextGenerationResponse();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of TextGenerationResponse
        /// </summary>
        [Test]
        public void TextGenerationResponseInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" TextGenerationResponse
            //Assert.IsInstanceOfType<TextGenerationResponse> (instance, "variable 'instance' is a TextGenerationResponse");
        }


        /// <summary>
        /// Test the property 'GeneratedText'
        /// </summary>
        [Test]
        public void GeneratedTextTest()
        {
            // TODO unit test for the property 'GeneratedText'
        }

    }

}
