/* 
 * Woolball AI Network API
 *
 * **Transform idle browsers into a powerful distributed AI inference network**  For detailed examples and model lists, visit our [GitHub repository](https://github.com/woolball-xyz/woolball-server).
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing TranslationRequestContract
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class TranslationRequestContractTests
    {
        // TODO uncomment below to declare an instance variable for TranslationRequestContract
        //private TranslationRequestContract instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of TranslationRequestContract
            //instance = new TranslationRequestContract();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of TranslationRequestContract
        /// </summary>
        [Test]
        public void TranslationRequestContractInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" TranslationRequestContract
            //Assert.IsInstanceOfType<TranslationRequestContract> (instance, "variable 'instance' is a TranslationRequestContract");
        }


        /// <summary>
        /// Test the property 'Model'
        /// </summary>
        [Test]
        public void ModelTest()
        {
            // TODO unit test for the property 'Model'
        }
        /// <summary>
        /// Test the property 'Dtype'
        /// </summary>
        [Test]
        public void DtypeTest()
        {
            // TODO unit test for the property 'Dtype'
        }
        /// <summary>
        /// Test the property 'Input'
        /// </summary>
        [Test]
        public void InputTest()
        {
            // TODO unit test for the property 'Input'
        }
        /// <summary>
        /// Test the property 'SrcLang'
        /// </summary>
        [Test]
        public void SrcLangTest()
        {
            // TODO unit test for the property 'SrcLang'
        }
        /// <summary>
        /// Test the property 'TgtLang'
        /// </summary>
        [Test]
        public void TgtLangTest()
        {
            // TODO unit test for the property 'TgtLang'
        }

    }

}
