/* 
 * Woolball AI Network API
 *
 * **Transform idle browsers into a powerful distributed AI inference network**  For detailed examples and model lists, visit our [GitHub repository](https://github.com/woolball-xyz/woolball-server).
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing TTSResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class TTSResponseTests
    {
        // TODO uncomment below to declare an instance variable for TTSResponse
        //private TTSResponse instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of TTSResponse
            //instance = new TTSResponse();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of TTSResponse
        /// </summary>
        [Test]
        public void TTSResponseInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" TTSResponse
            //Assert.IsInstanceOfType<TTSResponse> (instance, "variable 'instance' is a TTSResponse");
        }


        /// <summary>
        /// Test the property 'Audio'
        /// </summary>
        [Test]
        public void AudioTest()
        {
            // TODO unit test for the property 'Audio'
        }
        /// <summary>
        /// Test the property 'Format'
        /// </summary>
        [Test]
        public void FormatTest()
        {
            // TODO unit test for the property 'Format'
        }
        /// <summary>
        /// Test the property 'SampleRate'
        /// </summary>
        [Test]
        public void SampleRateTest()
        {
            // TODO unit test for the property 'SampleRate'
        }

    }

}
