/* 
 * Woolball AI Network API
 *
 * **Transform idle browsers into a powerful distributed AI inference network**  For detailed examples and model lists, visit our [GitHub repository](https://github.com/woolball-xyz/woolball-server).
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using RestSharp;
using IO.Swagger.Client;
using IO.Swagger.Model;

namespace IO.Swagger.Api
{
    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
        public interface ITranslationApi : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// Translation
        /// </summary>
        /// <remarks>
        /// Translate text between 200+ languages using NLLB models. Uses FLORES200 format for language codes.
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="model"></param>
        /// <param name="dtype"></param>
        /// <param name="input"></param>
        /// <param name="srcLang"></param>
        /// <param name="tgtLang"></param>
        /// <returns>TranslationResponse</returns>
        TranslationResponse Translation (string model, string dtype, string input, string srcLang, string tgtLang);

        /// <summary>
        /// Translation
        /// </summary>
        /// <remarks>
        /// Translate text between 200+ languages using NLLB models. Uses FLORES200 format for language codes.
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="model"></param>
        /// <param name="dtype"></param>
        /// <param name="input"></param>
        /// <param name="srcLang"></param>
        /// <param name="tgtLang"></param>
        /// <returns>ApiResponse of TranslationResponse</returns>
        ApiResponse<TranslationResponse> TranslationWithHttpInfo (string model, string dtype, string input, string srcLang, string tgtLang);
        #endregion Synchronous Operations
        #region Asynchronous Operations
        /// <summary>
        /// Translation
        /// </summary>
        /// <remarks>
        /// Translate text between 200+ languages using NLLB models. Uses FLORES200 format for language codes.
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="model"></param>
        /// <param name="dtype"></param>
        /// <param name="input"></param>
        /// <param name="srcLang"></param>
        /// <param name="tgtLang"></param>
        /// <returns>Task of TranslationResponse</returns>
        System.Threading.Tasks.Task<TranslationResponse> TranslationAsync (string model, string dtype, string input, string srcLang, string tgtLang);

        /// <summary>
        /// Translation
        /// </summary>
        /// <remarks>
        /// Translate text between 200+ languages using NLLB models. Uses FLORES200 format for language codes.
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="model"></param>
        /// <param name="dtype"></param>
        /// <param name="input"></param>
        /// <param name="srcLang"></param>
        /// <param name="tgtLang"></param>
        /// <returns>Task of ApiResponse (TranslationResponse)</returns>
        System.Threading.Tasks.Task<ApiResponse<TranslationResponse>> TranslationAsyncWithHttpInfo (string model, string dtype, string input, string srcLang, string tgtLang);
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
        public partial class TranslationApi : ITranslationApi
    {
        private IO.Swagger.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="TranslationApi"/> class.
        /// </summary>
        /// <returns></returns>
        public TranslationApi(String basePath)
        {
            this.Configuration = new IO.Swagger.Client.Configuration { BasePath = basePath };

            ExceptionFactory = IO.Swagger.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="TranslationApi"/> class
        /// </summary>
        /// <returns></returns>
        public TranslationApi()
        {
            this.Configuration = IO.Swagger.Client.Configuration.Default;

            ExceptionFactory = IO.Swagger.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="TranslationApi"/> class
        /// using Configuration object
        /// </summary>
        /// <param name="configuration">An instance of Configuration</param>
        /// <returns></returns>
        public TranslationApi(IO.Swagger.Client.Configuration configuration = null)
        {
            if (configuration == null) // use the default one in Configuration
                this.Configuration = IO.Swagger.Client.Configuration.Default;
            else
                this.Configuration = configuration;

            ExceptionFactory = IO.Swagger.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public String GetBasePath()
        {
            return this.Configuration.ApiClient.RestClient.Options.BaseUrl.ToString();
        }

        /// <summary>
        /// Sets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        [Obsolete("SetBasePath is deprecated, please do 'Configuration.ApiClient = new ApiClient(\"http://new-path\")' instead.")]
        public void SetBasePath(String basePath)
        {
            // do nothing
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public IO.Swagger.Client.Configuration Configuration {get; set;}

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public IO.Swagger.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        /// Gets the default header.
        /// </summary>
        /// <returns>Dictionary of HTTP header</returns>
        [Obsolete("DefaultHeader is deprecated, please use Configuration.DefaultHeader instead.")]
        public IDictionary<String, String> DefaultHeader()
        {
            return new ReadOnlyDictionary<string, string>(this.Configuration.DefaultHeader);
        }

        /// <summary>
        /// Add default header.
        /// </summary>
        /// <param name="key">Header field name.</param>
        /// <param name="value">Header field value.</param>
        /// <returns></returns>
        [Obsolete("AddDefaultHeader is deprecated, please use Configuration.AddDefaultHeader instead.")]
        public void AddDefaultHeader(string key, string value)
        {
            this.Configuration.AddDefaultHeader(key, value);
        }

        /// <summary>
        /// Translation Translate text between 200+ languages using NLLB models. Uses FLORES200 format for language codes.
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="model"></param>
        /// <param name="dtype"></param>
        /// <param name="input"></param>
        /// <param name="srcLang"></param>
        /// <param name="tgtLang"></param>
        /// <returns>TranslationResponse</returns>
        public TranslationResponse Translation (string model, string dtype, string input, string srcLang, string tgtLang)
        {
             ApiResponse<TranslationResponse> localVarResponse = TranslationWithHttpInfo(model, dtype, input, srcLang, tgtLang);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Translation Translate text between 200+ languages using NLLB models. Uses FLORES200 format for language codes.
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="model"></param>
        /// <param name="dtype"></param>
        /// <param name="input"></param>
        /// <param name="srcLang"></param>
        /// <param name="tgtLang"></param>
        /// <returns>ApiResponse of TranslationResponse</returns>
        public ApiResponse< TranslationResponse > TranslationWithHttpInfo (string model, string dtype, string input, string srcLang, string tgtLang)
        {
            // verify the required parameter 'model' is set
            if (model == null)
                throw new ApiException(400, "Missing required parameter 'model' when calling TranslationApi->Translation");
            // verify the required parameter 'dtype' is set
            if (dtype == null)
                throw new ApiException(400, "Missing required parameter 'dtype' when calling TranslationApi->Translation");
            // verify the required parameter 'input' is set
            if (input == null)
                throw new ApiException(400, "Missing required parameter 'input' when calling TranslationApi->Translation");
            // verify the required parameter 'srcLang' is set
            if (srcLang == null)
                throw new ApiException(400, "Missing required parameter 'srcLang' when calling TranslationApi->Translation");
            // verify the required parameter 'tgtLang' is set
            if (tgtLang == null)
                throw new ApiException(400, "Missing required parameter 'tgtLang' when calling TranslationApi->Translation");

            var localVarPath = "/api/v1/translation";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "multipart/form-data"
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (model != null) localVarFormParams.Add("model", this.Configuration.ApiClient.ParameterToString(model)); // form parameter
            if (dtype != null) localVarFormParams.Add("dtype", this.Configuration.ApiClient.ParameterToString(dtype)); // form parameter
            if (input != null) localVarFormParams.Add("input", this.Configuration.ApiClient.ParameterToString(input)); // form parameter
            if (srcLang != null) localVarFormParams.Add("srcLang", this.Configuration.ApiClient.ParameterToString(srcLang)); // form parameter
            if (tgtLang != null) localVarFormParams.Add("tgtLang", this.Configuration.ApiClient.ParameterToString(tgtLang)); // form parameter

            // make the HTTP request
            RestResponse localVarResponse = (RestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.Post, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("Translation", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<TranslationResponse>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                (TranslationResponse) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(TranslationResponse)));
        }

        /// <summary>
        /// Translation Translate text between 200+ languages using NLLB models. Uses FLORES200 format for language codes.
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="model"></param>
        /// <param name="dtype"></param>
        /// <param name="input"></param>
        /// <param name="srcLang"></param>
        /// <param name="tgtLang"></param>
        /// <returns>Task of TranslationResponse</returns>
        public async System.Threading.Tasks.Task<TranslationResponse> TranslationAsync (string model, string dtype, string input, string srcLang, string tgtLang)
        {
             ApiResponse<TranslationResponse> localVarResponse = await TranslationAsyncWithHttpInfo(model, dtype, input, srcLang, tgtLang);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Translation Translate text between 200+ languages using NLLB models. Uses FLORES200 format for language codes.
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="model"></param>
        /// <param name="dtype"></param>
        /// <param name="input"></param>
        /// <param name="srcLang"></param>
        /// <param name="tgtLang"></param>
        /// <returns>Task of ApiResponse (TranslationResponse)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<TranslationResponse>> TranslationAsyncWithHttpInfo (string model, string dtype, string input, string srcLang, string tgtLang)
        {
            // verify the required parameter 'model' is set
            if (model == null)
                throw new ApiException(400, "Missing required parameter 'model' when calling TranslationApi->Translation");
            // verify the required parameter 'dtype' is set
            if (dtype == null)
                throw new ApiException(400, "Missing required parameter 'dtype' when calling TranslationApi->Translation");
            // verify the required parameter 'input' is set
            if (input == null)
                throw new ApiException(400, "Missing required parameter 'input' when calling TranslationApi->Translation");
            // verify the required parameter 'srcLang' is set
            if (srcLang == null)
                throw new ApiException(400, "Missing required parameter 'srcLang' when calling TranslationApi->Translation");
            // verify the required parameter 'tgtLang' is set
            if (tgtLang == null)
                throw new ApiException(400, "Missing required parameter 'tgtLang' when calling TranslationApi->Translation");

            var localVarPath = "/api/v1/translation";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "multipart/form-data"
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (model != null) localVarFormParams.Add("model", this.Configuration.ApiClient.ParameterToString(model)); // form parameter
            if (dtype != null) localVarFormParams.Add("dtype", this.Configuration.ApiClient.ParameterToString(dtype)); // form parameter
            if (input != null) localVarFormParams.Add("input", this.Configuration.ApiClient.ParameterToString(input)); // form parameter
            if (srcLang != null) localVarFormParams.Add("srcLang", this.Configuration.ApiClient.ParameterToString(srcLang)); // form parameter
            if (tgtLang != null) localVarFormParams.Add("tgtLang", this.Configuration.ApiClient.ParameterToString(tgtLang)); // form parameter

            // make the HTTP request
            RestResponse localVarResponse = (RestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.Post, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("Translation", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<TranslationResponse>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                (TranslationResponse) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(TranslationResponse)));
        }

    }
}
